<h1>Meetup</h1>

<div class="row">
    <div class="col-md-12">
        <a href="<?= $this->url('meetup/add'); ?>" class="btn btn-primary">Add new</a>
    </div>

    <div class="col-md-12">
        <?php foreach ($this->meetups as $meetup): /* @var $meetups Meetup\Controller\IndexController */ ?>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            <a href="<?= $this->url('meetup') ."/". $meetup->getId(); ?>">
                                <?= $meetup->getTitle() ?>
                            </a>

                        </h3>
                    </div>
                    <div class="panel-body">
                        <p>
                            <strong>Date de début</strong> : <?= $meetup->getStartDate() ?>
                        </p>
                        <p>
                            <strong>Date de fin</strong>  : <?= $meetup->getEndDate() ?>
                        </p>
                        <p>
                            <strong>Organisé par</strong> : <?= $meetup->getOrganisateur() ?>
                        </p>
                        <p>
                            <strong>Entreprise</strong> : <?= $meetup->getEntreprise() ?>
                        </p>
                        <p>
                           <strong>Nombre de participant</strong>  : <?= $meetup->getParticipant() ?>
                        </p>
                        <p>
                            <strong>Description</strong> : <br>
                            <fieldset>
                                <?= $meetup->getDescription() ?>
                            </fieldset>

                        </p>
                        <p>
                            <a href="<?= $this->url('meetup/edit', ['id' => $meetup->getId()]); ?>"> edit</a>

                            <form action="<?php echo $this->url('meetup/delete'); ?>" method="post">
                                <input type="hidden" name="id" value="<?= $meetup->getId(); ?>">
                                <input type="submit" value="Delete">
                            </form>
                        </p>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
