<h1>Meetup</h1>

<div class="row">
    <div class="col-md-12">
        <a href="<?= $this->url('meetup/add'); ?>" class="btn btn-primary">Add new</a>
    </div>

    <div class="col-md-12">
        <?php foreach ($this->meetups as $meetup): /* @var $meetups Meetup\Controller\IndexController */ ?>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?= $meetup->getTitle() ?></h3>
                    </div>
                    <div class="panel-body">
                        <p>
                            Date : <?= $meetup->getDate() ?>
                        </p>
                        <p>
                            Organisé par : <?= $meetup->getOrganisateur() ?>
                        </p>
                        <p>
                            Entreprise : <?= $meetup->getEntreprise() ?>
                        </p>
                        <p>
                            Nombre de participant : <?= $meetup->getParticipant() ?>
                        </p>
                        <p>
                            <?= $meetup->getDescription() ?>
                        </p>

                        <p><a href="<?= $this->url('meetup/edit'); ?>"> edit</a> <a href="<?= $this->url('meetup/delete'); ?>/<?= $meetup->getId() ?>"> delete</a></p>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
